use_frameworks!

platform :ios, '10.0'

target 'BCJPrivateProtocolAlert_Example' do
  pod 'BCJPrivateProtocolAlert', :path => '../'

  target 'BCJPrivateProtocolAlert_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
